spring:
  datasource:
    url: jdbc:postgresql://db:5432/intern_task_book_store
    username: postgres
    password: cosu2362
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: coshqun23.62@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
